@url = https://localhost:7046

@userId = 5a4677f2-44a8-4cb2-b030-4351555dfda8

###
GET {{url}}/sport-events/{{userId}}

###
GET {{url}}/sport-events

###
POST {{url}}/sport-events
Content-Type: application/json

{
    "areaId": "5a4677f2-44a8-4cb2-b030-4351555dfda8",
    "sportType": "Basketball",
    "createdBy": "Dawid Pietrzak",
    "creationDate" : "2023-01-02T00:00:00.000Z",
    "eventStartDate" : "2023-01-03T00:00:00.000Z",
    "eventEndDate" : "2023-01-05T00:00:00.000Z"
}