@url = https://localhost:7046

@userId = v
@simpleUserId = 1

###
GET {{url}}/sport-events/{{userId}}

###
GET {{url}}/sport-events

###
POST {{url}}/sport-events
Content-Type: application/json

{
    "areaId": "77FB9668-BC26-4C96-9D10-ABEC6F283766",
    "sportType": "Basketball",
    "createdBy": "Dawid Pietrzak",
    "creationDate" : "2023-01-02T00:00:00.000Z",
    "eventStartDate" : "2023-01-02T00:00:00.000Z",
    "eventEndDate" : "2023-01-02T00:00:00.000Z"
}